apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
  internalTrafficPolicy:  Local # traffic policies for routing
  externalTrafficPolicy: Local
